### ISSUE TITLE
Fails to build with ld: warning and ld:error

### ISSUE THREAD

**Issue by commandline-be** [Aorimn/dislocker#177] opened 2019-06-06 17:38 UTC
version = v0.7.1
mbedtls = 2.0.0

make all
- - -
[  2%] Linking C shared library libdislocker.so
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): warning: relocation against `mbedtls_aes_crypt_ctr' in read-only section `.text'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/**ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_PC32 against symbol `mbedtls_aes_init' can not be used when making a shared object; recompile with -fPIC**
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/**ld: final link failed: Bad value
collect2: error: ld returned 1 exit status**
make[2]: *** [src/CMakeFiles/dislocker.dir/build.make:504: src/libdislocker.so.0.7.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: src/CMakeFiles/dislocker.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

- - - 

installed MbedTLS 2.0.0 as documented in INSTALL.md
not certain if the paragraph `Then apply the patch given by the following command:
git show 6f42417b library/CMakeLists.txt` is actually doing what i think it does

**Comment by Aorimn** [comment] 2020-11-18 06:21
The mbedtls latest version is 2.16, can you try to update your system? (which might already be the case as I'm replying a bit late, sorry)

**Comment by Aorimn** [comment] 2020-11-18 06:24
Duplicate of https://github.com/Aorimn/dislocker/issues/163

**Closed by Aorimn** 2020-11-18 06:24 UTC
Labels: duplicate
