### ISSUE TITLE
Compiling errors on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by acidrop** [Aorimn/dislocker#101] opened 2017-02-06 19:51 UTC
Hello,

I'm trying to compile dislocker on my environment (Ubuntu 16.04.1 LTS) and I'm getting the error below.
Could you please advise what I'm missing ?

Thanks
Yannis

```
~/git/dislocker$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yannis/git/dislocker
yannis@ubuntu:~/git/dislocker$ make
Scanning dependencies of target dislocker
[  2%] Building C object src/CMakeFiles/dislocker.dir/accesses/stretch_key.c.o
[  5%] Building C object src/CMakeFiles/dislocker.dir/accesses/accesses.c.o
[  7%] Building C object src/CMakeFiles/dislocker.dir/accesses/rp/recovery_password.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/accesses/user_pass/user_pass.c.o
[ 13%] Building C object src/CMakeFiles/dislocker.dir/encryption/encommon.c.o
[ 15%] Building C object src/CMakeFiles/dislocker.dir/encryption/decrypt.c.o
[ 18%] Building C object src/CMakeFiles/dislocker.dir/encryption/encrypt.c.o
[ 21%] Building C object src/CMakeFiles/dislocker.dir/encryption/aes-xts.c.o
[ 23%] Linking C shared library libdislocker.so
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker.dir/build.make:822: recipe for target 'src/libdislocker.so.0.6.1' failed
make[2]: *** [src/libdislocker.so.0.6.1] Error 1
CMakeFiles/Makefile2:239: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Aorimn** [comment] 2017-02-07 10:20
Hi,
This is a duplicate of #90. I'll try to make tests this week to ensure the develop branch is stable enough to be merged in the master one, and this should be fixed.

**Comment by Aorimn** [comment] 2017-02-08 17:15
Hi,
This should be fixed now, as a new version is out.

**Closed by Aorimn** 2017-02-08 17:15 UTC
Labels: duplicate, fixed-in-develop
