### ISSUE TITLE
[ERROR] The signature of the volume (001) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort. 

### ISSUE THREAD

**Issue by Schwingman** [Aorimn/dislocker#85] opened 2016-07-26 14:16 UTC
I get the above error when trying to mount. I understood that it had been fixed in new version / develop branch??(what is develop branch exactly?). But I still get the same error in latest dislocker.

What am I missing/how to fix?

**Comment by Aorimn** [comment] 2016-07-27 16:20
This error means that you probably didn't give the right partition to dislocker. This is not a bug, as far as I know, and hasn't been fixed in the develop branch of this git repository (which is what "develop branch" mean, you can read more about git [here](https://git-scm.com/)).

If you cannot find the right volume, the dislocker-find script can help you. If it still doesn't work, please paste the output of the `sudo fdisk -l` command.

**Comment by Schwingman** [comment] 2016-07-28 07:26
You are right. I am an idiot. Thanks for the help. It worked

**Comment by Aorimn** [comment] 2016-07-28 07:43
I'm glad it worked!

**Closed by Aorimn** 2016-07-28 07:43 UTC
