### ISSUE TITLE
build issue on ubuntu 

### ISSUE THREAD

**Issue by bletekk** [Aorimn/dislocker#90] opened 2016-10-01 10:05 UTC
Hi,

I'm trying to build dislocker on following Ubuntu system:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

... and get following linker error:

[ 78%] Linking C shared library libdislocker.so
cd /home/tku/dislocker/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/dislocker.dir/link.txt --verbose=
collect2: fatal error: ld terminated with signal 6 [Abgebrochen], core dumped
compilation terminated.
/usr/bin/ld: ld: wcsrtombs.c:94: __wcsrtombs: Zusicherung »data.__outbuf[-1] == '\0'« nicht erfüllt.
src/CMakeFiles/dislocker.dir/build.make:796: die Regel für Ziel „src/libdislocker.so.0.6.1“ scheiterte
make[2]: **\* [src/libdislocker.so.0.6.1] Fehler 1
make[2]: **\* Datei „src/libdislocker.so.0.6.1“ wird gelöscht
CMakeFiles/Makefile2:200: die Regel für Ziel „src/CMakeFiles/dislocker.dir/all“ scheiterte
make[1]: **\* [src/CMakeFiles/dislocker.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: **\* [all] Fehler 2

I'm using a german localized system. Do you have any advice on that?

Best Regards

bletekk

PS
output of "LANG=C make"
[ 78%] Linking C shared library libdislocker.so
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker.dir/build.make:796: recipe for target 'src/libdislocker.so.0.6.1' failed
make[2]: **\* [src/libdislocker.so.0.6.1] Error 1
CMakeFiles/Makefile2:200: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed
make[1]: **\* [src/CMakeFiles/dislocker.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by rewolff** [comment] 2016-10-01 17:23
It would be preferable for us (ehhh... the developers) to see the output of 
`  LANG=C make 
`

**Comment by Aorimn** [comment] 2016-10-07 21:03
That would be much helpful for the next time, indeed. However, I think I've found the same error here: http://stackoverflow.com/questions/25665273/core-dumped-while-creating-shared-library

That's interesting, because dislocker should build with the `-fPIC` flag. I'll try to take some time to reproduce it next week, but I won't guarantee it.

**Comment by rewolff** [comment] 2016-10-09 07:12
By the way, I was finally able to compile it on my friend's Xenial system. But it wasn't simple. Shitty memory: I forgot what was required in the end. :-( 
Sorry.

**Comment by Aorimn** [comment] 2016-10-09 08:32
@rewolff Did you make any change to dislocker?

**Comment by rewolff** [comment] 2016-10-09 09:08
I'll try to figure that out. If anything, it was stuff like makefiles, not the actual code.

**Comment by Aorimn** [comment] 2016-10-23 17:05
It seems to work from a freshly installed ubuntu 16.04, using the "develop" branch of the repository.

@bletekk can you confirm it works for you?

**Comment by rewolff** [comment] 2016-10-23 19:41
I do rember that it was something simple in the end. Like switching to "develop".

Maybe documenting the compilation errrors with "need to switch to develop" as the solution would help. Or marking "master" as "not compatible with Ubuntu 16.04, use develop".

**Comment by Aorimn** [comment] 2016-10-23 19:46
Or that I merge develop into master, after enough testing to ensure develop is stable enough :)

**Comment by rewolff** [comment] 2016-10-23 20:20
My friend wrote: 
> Joepie, dislocker werkt weer!!
> Reuze bedankt, je bent geweldig!!!
so she's confirmed it works. :-)

**Comment by Aorimn** [comment] 2016-10-23 20:33
Awesome :)

**Comment by Aorimn** [comment] 2017-02-08 17:16
Hi,
This should be fixed now, as a new version is out.

**Closed by Aorimn** 2017-02-08 17:16 UTC
Labels: bug, fixed-in-develop

**Comment by acidrop** [comment] 2017-02-08 22:33
Hello,

I'm afraid I have the same behaviour even with  the latest version. Tried both master and develop branch.

```
~/git/dislocker$ git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
yannis@ubuntu:~/git/dislocker$ cmake .
PolarSSL/mbedTLS version: 2.4.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yannis/git/dislocker
yannis@ubuntu:~/git/dislocker$ make
Scanning dependencies of target dislocker
[  2%] Building C object src/CMakeFiles/dislocker.dir/dislocker.c.o
[  5%] Building C object src/CMakeFiles/dislocker.dir/common.c.o
[  7%] Building C object src/CMakeFiles/dislocker.dir/config.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdio.c.o
[ 13%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdlib.c.o
[ 15%] Building C object src/CMakeFiles/dislocker.dir/metadata/datums.c.o
[ 18%] Building C object src/CMakeFiles/dislocker.dir/metadata/metadata.c.o
[ 21%] Building C object src/CMakeFiles/dislocker.dir/metadata/vmk.c.o
[ 23%] Building C object src/CMakeFiles/dislocker.dir/metadata/fvek.c.o
[ 26%] Building C object src/CMakeFiles/dislocker.dir/metadata/extended_info.c.o
[ 28%] Building C object src/CMakeFiles/dislocker.dir/metadata/guid.c.o
[ 31%] Building C object src/CMakeFiles/dislocker.dir/metadata/print_metadata.c.o
[ 34%] Building C object src/CMakeFiles/dislocker.dir/accesses/stretch_key.c.o
[ 36%] Building C object src/CMakeFiles/dislocker.dir/accesses/accesses.c.o
[ 39%] Building C object src/CMakeFiles/dislocker.dir/accesses/rp/recovery_password.c.o
[ 42%] Building C object src/CMakeFiles/dislocker.dir/accesses/user_pass/user_pass.c.o
[ 44%] Building C object src/CMakeFiles/dislocker.dir/accesses/bek/bekfile.c.o
[ 47%] Building C object src/CMakeFiles/dislocker.dir/encryption/encommon.c.o
[ 50%] Building C object src/CMakeFiles/dislocker.dir/encryption/decrypt.c.o
[ 52%] Building C object src/CMakeFiles/dislocker.dir/encryption/encrypt.c.o
[ 55%] Building C object src/CMakeFiles/dislocker.dir/encryption/diffuser.c.o
[ 57%] Building C object src/CMakeFiles/dislocker.dir/encryption/crc32.c.o
[ 60%] Building C object src/CMakeFiles/dislocker.dir/encryption/aes-xts.c.o
[ 63%] Building C object src/CMakeFiles/dislocker.dir/ntfs/clock.c.o
[ 65%] Building C object src/CMakeFiles/dislocker.dir/ntfs/encoding.c.o
[ 68%] Building C object src/CMakeFiles/dislocker.dir/inouts/inouts.c.o
[ 71%] Building C object src/CMakeFiles/dislocker.dir/inouts/prepare.c.o
[ 73%] Building C object src/CMakeFiles/dislocker.dir/inouts/sectors.c.o
[ 76%] Building C object src/CMakeFiles/dislocker.dir/ruby.c.o
[ 78%] Linking C shared library libdislocker.so
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker.dir/build.make:822: recipe for target 'src/libdislocker.so.0.7.1' failed
make[2]: *** [src/libdislocker.so.0.7.1] Error 1
CMakeFiles/Makefile2:239: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Aorimn** [comment] 2017-02-09 12:37
Weird, I just tested it on an up-to-date 16.04 and didn't have any problem.
However, looking at your output, it seems we don't link dislocker with the same mbedtls library. Using `make VERBOSE=1`, I'm seeing that I link with /usr/lib/x86_64-linux-gnu/libmbedcrypto.so, not /usr/local/lib/mbedcrypto.a as you. How did you install mbedtls?

**Comment by acidrop** [comment] 2017-02-09 14:12
You are right, my mbedtls library files are located in /usr/local/lib instead of  /usr/lib/x86_64-linux-gnu.
I've compiled mbedtls from source since it was not available on ubuntu repos. How I should define to mbedtls to put the library files into /usr/lib/x86_64-linux-gnu ?

Thanks

**Comment by Aorimn** [comment] 2017-02-09 14:48
Indeed, I had to add the universe and the multiverse repositories to apt to get mbedtls to install on ubuntu. According to https://launchpad.net/ubuntu/xenial/+source/mbedtls the universe repo might be sufficient.

**Comment by acidrop** [comment] 2017-02-09 17:35
Thanks! that worked...

**Comment by Aorimn** [comment] 2017-02-09 17:46
Awesome! You made me worried for a moment :-)
